public enum FileType {
      EXCEL,
      EXCEL_OPTION,
      TEXT_PIPE_USAGE,
      TEXT_PIPE_CUSTOMER,
      TEXT_PIPE_ITEM,

      TEXT_BANG_USAGE,
      TEXT_BANG_CUSTOMER,
      TEXT_BANG_ITEM,

      TEXT_TAB_USAGE,
      TEXT_TAB_CUSTOMER,
      TEXT_TAB_ITEM,

      TEXT_CAT_USAGE,
      TEXT_CAT_CUSTOMER,
      TEXT_CAT_ITEM,

      TEXT_SYS_USAGE,
      TEXT_SYS_CUSTOMER,
      TEXT_SYS_ITEM,

      TEXT_OPTION_USAGE,
      TEXT_OPTION_CUSTOMER,
      TEXT_OPTION_ITEM

}
